---
- name: Install Apache and Upload my web page
  hosts: all
  become: true

  vars:
    source_file: ./mysite/index.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=installed

  - name: Copy my home page to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start Web Servers and make it Enabled on startup
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: Restart Apache 
    service: name=apache2 state=restarted
