---
- name: Install Apache Web Server
  hosts: all
  become: true

  tasks:
  - name: Install Apache
    apt: name=apache2 state=installed

  - name: Apache Start and Enable
    service: name=apache2 state=started enabled=yes
