---
- name: Install Apache and Upload my web page
  hosts: all
  become: true

  vars:
    source_folder: ./mysite2
    destin_folder: /var/www/html

  tasks:
  - name:  Check and Print LINUX version
    debug: var=ansible_os_family

  - block: # ===FOR REDHAT===
    - name: Install Apache Web Server for RedHat
      yum: name=httpd state=latest
    - name: Start Web Server and make it Enabled for RedHat
      service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - block: # ===FOR DEBIAN===
     - name: Install Apache Web Server for Debian
       apt: name=apache2 state=latest
     - name: Start Web Server and make it Enabled for Debian
       service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  - name: Generate index.html file
    template: src={{ source_folder }}/index.j2 dest={{ destin_folder }}/index.html mode=0644
    notify:
      - Restart Apache RedHat
      - Restart Apache Debian

  - name: Copy my home page to Servers RedHat
    copy: src={{ source_folder }}/{{ item }} dest={{ destin_folder }} mode=0644
    loop:
      - "simba.JPG"
    notify: 
      - Restart Apache RedHat
      - Restart Apache Debian


  handlers:
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"


  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

