---
- name: My Super Puper Playbook for Variables Lesson
  hosts: all
  become: true


  vars:
    message1: Privet
    message2: World!
    secret: ASdqwe123

  tasks:
  - name: Print Secret Var
    debug:
      var: secret

  - debug:
      msg: "Secretnoe slovo: {{ secret }}"

  - debug:
      msg: "Vladelec etogo servers -->{{ owner }}<--"

  - set_fact: full_message="{{ message1 }} {{ message2}} from {{ owner }}"

  - debug:
      var: full_message

  - debug:
      var: ansible_os_family

  - shell: uptime
    register: result

  - debug:
      var: result.stdout
